In [2]:
import tensorflow as tf

In [8]:
# Initialization of tensor
x = tf.constant(4 , shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [12]:
x = tf.constant([[1,2,3], [4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [11]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [14]:
x = tf.zeros((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [15]:
x = tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [19]:
x = tf.random.normal((3,3), mean=0, stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.6409539 , -0.18613347, -1.7850485 ],
       [-0.28492668,  1.2425716 , -0.36823976],
       [ 0.39825153,  0.06603312, -1.1670808 ]], dtype=float32)>

In [20]:
tf.random.uniform((1,3), minval=0, maxval=1)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.98623884, 0.43461633, 0.8765528 ]], dtype=float32)>

In [21]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>